# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')
Import('cppEnv')

cflags=' -DIS_LITTLE_ENDIAN  -DIS_LINUX  -D_REENTRANT  -DHAVE_STD_STRING_VIEW '

# cflags+='-DSDL_IMAGE_USE_COMMON_BACKEND \
# 		-DLOAD_BMP -DLOAD_GIF -DLOAD_LBM -DLOAD_PCX -DLOAD_PNM \
# 		-DLOAD_SVG -DLOAD_TGA -DLOAD_XCF -DLOAD_XPM -DLOAD_XV \
# 		 -DLOAD_PNG -DLOAD_WEBP\
#         -DLOAD_JPG  -DFAST_IS_JPEG\
#         '

libs = [
    'libgaga.a',

]+env['LIBC']

include = [
    '../../eggs/libcxx/include',
    '../../eggs/libcxxabi/include',

    '../../eggs/libgaga',
    'include',
    '.',
]

libpath = [
    '../../eggs/libgaga/',
]

source = ['service_a.c']

env.Program('servicea', source,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=libpath +env['LIBPATH'],
    CPPPATH=include+ env['CPPPATH'] ,
    CFLAGS=cflags+' $CFLAGS $LIBCFLAGS ',
    CXXFLAGS=cflags+' $CXXFLAGS $LIBCFLAGS '
            )


source = ['service_b.c']

env.Program('serviceb', source,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=libpath +env['LIBPATH'],
    CPPPATH=include+ env['CPPPATH'] ,
    CFLAGS=cflags+' $CFLAGS $LIBCFLAGS ',
    CXXFLAGS=cflags+' $CXXFLAGS $LIBCFLAGS '
            )


source = ['vfsd.c']

env.Program('vfsd', source,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=libpath +env['LIBPATH'],
    CPPPATH=include+ env['CPPPATH'] ,
    CFLAGS=cflags+' $CFLAGS $LIBCFLAGS ',
    CXXFLAGS=cflags+' $CXXFLAGS $LIBCFLAGS '
            )

source = ['systemd.c']

env.Program('systemd', source,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=libpath +env['LIBPATH'],
    CPPPATH=include+ env['CPPPATH'] ,
    CFLAGS=cflags+' $CFLAGS $LIBCFLAGS ',
    CXXFLAGS=cflags+' $CXXFLAGS $LIBCFLAGS '
            )

