# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os
import platform
import copy

Import('appEnv')

env=appEnv

returns=[]


if env.get('APP'):
    SConscript(dirs=['tinyusb'], exports='env')
    SConscript(dirs=['wifi'], exports='env')
    SConscript(dirs=['bluetooth'], exports='env')
else:
    pass

Export('appEnv')

Return('returns')
