# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('cliEnv')

env=cliEnv

cflags = '  '
libs = [
    'gaga',

]+env['LIBC']

include = [
    '../../eggs/libgaga',
    'include',
    '.',
    'src',
    'hw',
    'hw/bsp'
]

libpath = [
    '#/eggs/libgaga/',
]

source = []

source += [
    
]

# env.Program('wifi', source,
#             LIBS=libs+env.get('LIBS'),
#             LIBPATH=libpath + env['LIBPATH'],
#             CPPPATH=include + env['CPPPATH'],
#             CFLAGS=cflags+' $CFLAGS $LIBCFLAGS ',
#             CXXFLAGS=cflags+' $CXXFLAGS $LIBCFLAGS '
#             )
